apiVersion: v1
kind: Service # Create the Kubernetes Service
metadata:
  name: sit323-2025-prac6p-service # Name of the Service
spec:
  type: NodePort # Exposes service on each Node's IP at a static port 
  selector:
    app: sit323-2025-prac6p # Match this label with the pods 
  ports:
    - port: 80
      targetPort: 3040
      nodePort: 30000
      